docs/linux/concepts/loops.md
Just fixing a simple typo I found while reading the new open coded iterators page.
=> Fix typo on kernel commit URL

docs/linux/helper-function/bpf_ringbuf_discard.md, docs/linux/helper-function/bpf_ringbuf_output.md, docs/linux/helper-function/bpf_ringbuf_query.md, docs/linux/helper-function/bpf_ringbuf_reserve.md, docs/linux/helper-function/bpf_ringbuf_reserve_dynptr.md, docs/linux/helper-function/bpf_ringbuf_submit.md, docs/linux/helper-function/bpf_ringbuf_submit_dynptr.md
Titles of bpf_ringbuf function pages are all the same; now they are proper.
=> Fix titles of bpf_ringbuf functions

docs/linux/helper-function/bpf_ringbuf_discard.md, docs/linux/helper-function/bpf_ringbuf_output.md, docs/linux/helper-function/bpf_ringbuf_query.md, docs/linux/helper-function/bpf_ringbuf_reserve.md, docs/linux/helper-function/bpf_ringbuf_submit.md
PR #18 updated the symbols and headers of the ringbuf helper functions which were incorrect before. This commit follows up by regenerating the hyperlinks of the version number links.
=> Update ringbuf helper version links

docs/linux/syscall/BPF_PROG_TEST_RUN.md
The docs said that the `duration` field was the total run time when tests are repeated, but it actually contains the already avaraged value.
=> syscall: Correcting `duration` description in BPF_PROG_TEST_RUN

docs/linux/helper-function/bpf_clone_redirect.md, docs/linux/helper-function/bpf_redirect.md
I recently used the bpf_redirect and bpf_clone_redirect helpers and therefore added a small example for each of them to the docs.
=> Add examples for bpf_clone_redirect and bpf_redirect

Makefile, docs/linux/program-type/BPF_PROG_TYPE_XDP.md, go.mod, mkdocs.yml, tools/mtu-calc/const.go, tools/mtu-calc/drivers.go, tools/mtu-calc/macro.go, tools/mtu-calc/main.go, tools/mtu-calc/table.go, tools/mtu-calc/vars.go
It turns out that every NIC driver enforces a different maximum MTU. This commit adds a table that allows users to see the maximum MTU for each driver on different platforms, with and without fragments enabled.
Fixes: #17
=> program-type/BPF_PROG_TYPE_XDP.md: Add max MTU table

docs/linux/concepts/loops.md
The `bpf_for` macro needs an integer as the loop counter, not an integer pointer. Otherwise, we get a cast error from int to int*.
=> Correction for bpf_for example

data/feature-versions.yaml, data/kfuncs.yaml, docs/linux/kfuncs/SUMMARY.md, docs/linux/kfuncs/bpf_arena_alloc_pages.md, docs/linux/kfuncs/bpf_arena_free_pages.md, docs/linux/kfuncs/index.md, docs/linux/program-type/BPF_PROG_TYPE_CGROUP_SKB.md, docs/linux/program-type/BPF_PROG_TYPE_CGROUP_SOCK_ADDR.md, docs/linux/program-type/BPF_PROG_TYPE_LSM.md, docs/linux/program-type/BPF_PROG_TYPE_LWT_IN.md, docs/linux/program-type/BPF_PROG_TYPE_LWT_OUT.md, docs/linux/program-type/BPF_PROG_TYPE_LWT_XMIT.md, docs/linux/program-type/BPF_PROG_TYPE_SCHED_CLS.md, docs/linux/program-type/BPF_PROG_TYPE_SK_SKB.md, docs/linux/program-type/BPF_PROG_TYPE_SOCKET_FILTER.md, docs/linux/program-type/BPF_PROG_TYPE_STRUCT_OPS.md, docs/linux/program-type/BPF_PROG_TYPE_SYSCALL.md, docs/linux/program-type/BPF_PROG_TYPE_TRACING.md, docs/linux/program-type/BPF_PROG_TYPE_XDP.md, tools/version-finder/patterns.yaml
This commit adds two new kfuncs, bpf_arena_alloc_pages and bpf_arena_free_pages. These kfuncs are used to allocate and free pages from BPF arenas.
=> kfuncs: Add bpf_arena_alloc_pages and bpf_arena_free_pages kfuncs

docs/SUMMARY.md, docs/concepts/btf.md, docs/concepts/core.md, docs/concepts/index.md
I take the plunge.
I've tried to synthetize without losing as much detail as possible 
- Add documentation for BPF CO-RE
- Add documentation for BTF
There are still a few things missing:
Questions about files : `instruction-set.md` and `loader.md` what is expected ?
=> Add BPF CORE and BTF documentation

.gitignore, docs/linux/helper-function/bpf_ringbuf_discard.md, docs/linux/helper-function/bpf_ringbuf_output.md, docs/linux/helper-function/bpf_ringbuf_query.md, docs/linux/helper-function/bpf_ringbuf_reserve.md, docs/linux/helper-function/bpf_ringbuf_submit.md
=> helper-function: Usage and examples for ring buffers

.aspell.en.pws, data/helpers-functions.yaml, docs/linux/map-type/BPF_MAP_TYPE_RINGBUF.md, docs/linux/map-type/index.md, docs/stylesheets/extra.css
Add the contents for the `BPF_MAP_TYPE_RINGBUF`. Also modified the helper functions data file to correctly generate the list of supported helpers.
=> map-type: Add `BPF_MAP_TYPE_RINGBUF` page contents

docs/linux/concepts/kfuncs.md, docs/linux/helper-function/index.md, docs/linux/index.md, docs/linux/kfuncs/index.md
Document stability guarantees of the helper functions being coupled to the same stability guarantees of the Linux Kernel (Userspace) API.
Also document that these guarantees do not apply to KFuncs.
=> docs: document helper function stability

.github/workflows/deploy-gh-pages.yaml
This action will build the docs and deploy them to the `gh-pages` branch on push to the `master` branch. Github Pages will pickup and host the docs from the `gh-pages` branch.
=> .github: Add deploy action for gh-pages

.github/workflows/deploy-gh-pages.yaml, mkdocs.yml, requirements.txt, tools/Dockerfile
This commit adds the `social` plugin which generates social cards for every page. These are essentially PNG images which will be displayed when the page is shared on social media platforms.
This is just the basic setup to get something going.
=> Add social cards to the website

data/helpers-functions.yaml, docs/linux/helper-function/bpf_get_attach_cookie.md, docs/linux/program-type/BPF_PROG_TYPE_LSM.md, docs/linux/program-type/BPF_PROG_TYPE_RAW_TRACEPOINT.md, docs/linux/program-type/BPF_PROG_TYPE_TRACING.md, mkdocs.yml
In v5.19, cookie support was added to `BPF_PROG_TYPE_TRACING` and `BPF_PROG_TYPE_LSM`. This isn't reflected in the man pages and wasn't in our docs. This commit fixes both the description and program <-> helper function indexes.
=> helper-functions: Update `bpf_get_attach_cookie` info

docs/linux/helper-function/bpf_for_each_map_elem.md
Hello. I wrote an example for `bpf_for_each_map_elem` helper function.
=> linux/helper-function Add example for bpf_for_each_map_elem

docs/linux/concepts/kfuncs.md
Added a few version tags for the different kfunc parameter annotations. Also added the `__map` parameter annotation which has added since the last time I updated the concept page.
=> concepts: Updated the kfuncs concept page

docs/linux/helper-function/bpf_get_current_comm.md, docs/linux/helper-function/bpf_probe_write_user.md, docs/linux/helper-function/bpf_strncmp.md
add prog examples for:
* `bpf_probe_write_user`
* `bpf_get_current_comm`
* `bpf_strncmp`
=> update(helpers): add examples for some eBPF helpers

.aspell.en.pws, Makefile, docs/ebpf-library/libbpf/SUMMARY.md, docs/ebpf-library/libbpf/userspace/SUMMARY.md, docs/ebpf-library/libbpf/userspace/index.md, docs/ebpf-library/libbpf/userspace/libbpf_major_version.md, docs/ebpf-library/libbpf/userspace/libbpf_minor_version.md, docs/ebpf-library/libbpf/userspace/libbpf_strerror.md, docs/linux/helper-function/bpf_get_smp_processor_id.md, docs/linux/helper-function/bpf_kptr_xchg.md, docs/linux/helper-function/bpf_loop.md, docs/linux/helper-function/bpf_override_return.md, docs/linux/helper-function/bpf_setsockopt.md, tools/libbpf-tag-gen/main.go, tools/spellcheck/main.go
The PR adds a new tool to generate Libbpf version tags for userspace API functions. To prove it works, this PR also adds a few pages. Stumbled across a spellcheck usage issue while running it on the new pages and fixed it. And while running the `make generate-docs` we got some helper function updates which I decided to also commit while at it.
=> tools: Add libbpf tag gen tool

docs/linux/concepts/af_xdp.md
Hello,
this PR has a number of fixes for the AF_XDP concept page.
The first commit is a collection of typos. I think they are not controversial, so I put them together.
The second commit homogenize the article before the word XDP; before, sometimes it was "a xdp", sometimes it was "an XDP".
The third commit swaps therefor to therefore for clarify.
Finally, the fourth commit fixes two C code samples regarding the use of `sizeof()` with structures.
PS: Following the same rule as commit 2, we should also use "An XSK". But, for this acronym, the text always used "a XDK". So i did not think it was worth changing it.
=> linux/concept: af-xdp concept fixes

docs/linux/program-type/BPF_PROG_TYPE_NETFILTER.md
The netfilter program context is a bit unusual in the sense that its context is an unstable type which isn't available via user API header files. Users are expected to get the context via vmlinux.
This was not explained well enough, so this commit adds some details.
=> program-type: Add some clarification around netfilter contexts

.aspell.en.pws, docs/ebpf-library/libbpf/ebpf/SUMMARY.md, docs/ebpf-library/libbpf/ebpf/__always_inline.md, docs/ebpf-library/libbpf/ebpf/__hidden.md, docs/ebpf-library/libbpf/ebpf/__kconfig.md, docs/ebpf-library/libbpf/ebpf/__kptr.md, docs/ebpf-library/libbpf/ebpf/__kptr_untrusted.md, docs/ebpf-library/libbpf/ebpf/__ksym.md, docs/ebpf-library/libbpf/ebpf/__noinline.md, docs/ebpf-library/libbpf/ebpf/__percpu_kptr.md, docs/ebpf-library/libbpf/ebpf/__weak.md, docs/ebpf-library/libbpf/ebpf/index.md
This commit adds pages for the __xxx attribute macros that are available in the bpf_helpers.h header file.
=> libbpf/ebpf: Add attribute macros pages

docs/linux/map-type/BPF_MAP_TYPE_BLOOM_FILTER.md, docs/linux/map-type/BPF_MAP_TYPE_HASH.md, docs/linux/map-type/BPF_MAP_TYPE_LRU_HASH.md, docs/linux/map-type/BPF_MAP_TYPE_PERCPU_HASH.md
From the context, it appears to me that the description about hash map operations should say that they are usually inherently random "at access time". The original "in access time" doesn't really make sense to me. Or do I misunderstand the sentence?
=> map-type: Fix preposition for BPF_F_ZERO_SEED

.github/workflows/deploy-gh-pages.yaml
After recent changes to CI, it seems that the deploy workflow causes mixed permissions. Sidestep that protection by marking the mounted directory as a git safe directory.
=> .github/workflows: Git safe directory

.github/workflows/deploy-gh-pages.yaml
By default the repo was getting checked out at a depth of 1 which means we do not have the full git history. This caused the git commiters plugin to see all files as being added and updated at the current timestamp. This caused the footer to render incorrectly and the cache to be ineffective. This PR solves both issues.
=> Deploy workflow checkout with full depth

.aspell.en.pws, docs/linux/concepts/SUMMARY.md, docs/linux/concepts/index.md, docs/linux/concepts/trampolines.md, docs/linux/program-type/BPF_PROG_TYPE_EXT.md, docs/linux/program-type/BPF_PROG_TYPE_TRACING.md
This PR adds a concept page for BPF trampolines, the mechanism behind fentry/fexit/fmod_ret programs, freplace programs and LSM programs.
=> linux/concepts: Add trampolines concept page

docs/linux/concepts/concurrency.md
See more details in the specification[^0]:
> The BPF_FETCH modifier is optional for simple atomic operations, and
always set for the complex atomic operations. If the BPF_FETCH flag is set, then the operation also overwrites src with the value that was in memory before it was modified.
Note that we could be even more explicit like they do with something like: "value that was in memory before it was modified".
[^0]: https://www.kernel.org/doc/html/v6.5/bpf/instruction-set.html#atomic-operations
=> linux/concepts: fix a mistake on atomics return value

.gitignore, data/feature-versions.yaml, docs/linux/program-type/BPF_PROG_TYPE_SCHED_CLS.md, docs/linux/syscall/BPF_LINK_CREATE.md, docs/linux/timeline/index.md
The table of attach types in the BPF_PROG_TYPE_SCHED_CLS.md page was not parsed and a bit messy, I therefore simplified it to only keep the currently supported attach types. I included these new attach types in the feature versions tracking file.
=> Improve BPF_PROG_TYPE_SCHED_CLS

docs/linux/program-type/BPF_PROG_TYPE_STRUCT_OPS/hid_bpf_ops.md, docs/linux/program-type/BPF_PROG_TYPE_STRUCT_OPS/sched_ext_ops.md, docs/linux/program-type/BPF_PROG_TYPE_STRUCT_OPS/tcp_congestion_ops.md
The metadata on the struct_ops pages was incorrect, due to a copy paste mistake.
=> Fix metadata on struct_ops pages

docs/linux/concepts/trampolines.md
This commit adds a little bit more explanation around the usage of `NOP` instructions, including some pseudo-assembly to explain the concept better.
Fixes: #113
=> concepts/trampolines.md: Improve trampoline explanation

docs/linux/concepts/kfuncs.md
I was reading that page and just saw that little typo
=> kfuncs: fix a small typo in the kfuncs concept page

docs/linux/syscall/BPF_MAP_LOOKUP_BATCH.md
The last line in the `out_batch` section is missing some text. I just added some, but feel free to edit my commit or replace it entirely with your own fix.
=> linux/syscall: add missing text to BPF_MAP_LOOKUP_BATCH

docs/linux/kfuncs/bpf_sock_destroy.md
The bpf_sock_destroy kfunc can be called on BPF_PROG_TYPE_TRACING program types but is in reality restricted to BPF_TRACE_ITER attach type.
=> kfuncs: add note on bpf_sock_destroy only supported attach type

docs/linux/map-type/BPF_MAP_TYPE_CGROUP_ARRAY.md, docs/linux/map-type/BPF_MAP_TYPE_HASH_OF_MAPS.md, docs/linux/map-type/BPF_MAP_TYPE_LRU_PERCPU_HASH.md, docs/linux/map-type/BPF_MAP_TYPE_USER_RINGBUF.md, docs/linux/program-type/BPF_PROG_TYPE_LIRC_MODE2.md, docs/linux/program-type/BPF_PROG_TYPE_LWT_SEG6LOCAL.md
While the documentation page for these map/program types is still empty, at least document the kernel version/commit they were added in so provide some initial context.
=> docs/linux: add missing feature tags for map/program types

go.mod, go.sum
Fixes: https://github.com/isovalent/ebpf-docs/security/dependabot/2
=> go.mod: Upgrade golang.org/x/net to v0.36.0

docs/linux/helper-function/bpf_probe_read_kernel_str.md, docs/linux/helper-function/bpf_probe_read_user_str.md
This PR adds a detailed usage explanation and example for the helper function `bpf_probe_read_kernel_str`. The update improves the documentation by providing a clear demonstration of how to use the function.
**Previous documentation:**
**Updated documentation:**
**Previous documentation:**
**Updated documentation:**
- Helps new users understand how to use `bpf_probe_read_kernel_str` effectively.
This is my first contribution to eBPF documentation, so feedback is highly appreciated! If any improvements are needed, I’m happy to adjust accordingly.
=> Add the usage and example part to the helper function bpf_probe_read_kernel_str

.aspell.en.pws, docs/linux/program-type/BPF_PROG_TYPE_LIRC_MODE2.md
Add some basic information for this program type. Missing more detailed attachment information, and lists of available helper functions/kfuncs.
All of this information is from [LIRC kernel docs](https://docs.kernel.org/userspace-api/media/rc/lirc-dev-intro.html).
=> Add BPF_PROG_TYPE_LIRC_MODE2 documentation

docs/linux/program-type/BPF_PROG_TYPE_PERF_EVENT.md, docs/linux/program-type/BPF_PROG_TYPE_TRACEPOINT.md, docs/linux/syscall/BPF_BTF_LOAD.md, docs/linux/syscall/BPF_LINK_CREATE.md, docs/linux/syscall/BPF_MAP_CREATE.md, docs/linux/syscall/BPF_PROG_LOAD.md
Revisit the create / load syscall pages for the BPF objects. Updated added fields and flags. Also updated the C defintions and added links from the code to their respective sections.
=> linux/syscall: Update create and load syscall pages

README.md, contributions-guide.md, docs/SUMMARY.md, docs/meta.md, mkdocs.yml
This commit adds meta docs (docs about our docs) which explain the particulars of how this project works to make it easier for people to get started.
=> docs/meta: Add meta docs

docs/linux/syscall/BPF_LINK_CREATE.md
This syscall command *creates* a new BPF link.
=> Fixed Minor Typo

docs/ebpf-library/libbpf/userspace/bpf_program__attach_uprobe_multi.md
docs(userspace/bpf_program__attach_uprobe_multi): remove typo in attach function args
The ref_ctr_offsets argument to the bpf_program__attach_uprobe_multi
lbbpf function for attching multiple uprobes via multi link, wrongly
referenced the cookies
=> docs(bpf_program__attach_uprobe_multi): remove typo in attach args

docs/linux/concepts/concurrency.md
Support for atomic operations other than ADD were added only with Linux 5.12. The docs for concurrency have been extended with a version tag to make this explicit.
=> Add version tags to atomic operations

.aspell.en.pws, docs/linux/helper-function/bpf_get_current_cgroup_id.md, docs/linux/helper-function/bpf_get_current_comm.md, docs/linux/helper-function/bpf_get_current_pid_tgid.md, docs/linux/helper-function/bpf_get_current_uid_gid.md
Add usage examples for bpf_get_current_cgroup_id, bpf_get_current_comm, bpf_get_current_uid_gid and bpf_get_current_pid_tgid
=> Add usage examples for helper functions

docs/ebpf-library/libbpf/ebpf/PT_REGS_PARM_SYSCALL.md, docs/ebpf-library/libbpf/ebpf/PT_REGS_SYSCALL_REGS.md, docs/ebpf-library/libbpf/ebpf/SUMMARY.md, docs/ebpf-library/libbpf/ebpf/index.md
Added an example to the `PT_REGS_SYSCALL_REGS` documentation. Also improve the usage section of that page a bit.
Discovered the page for `PT_REGS_PARM_SYSCALL` was missing, so I added that as well.
=> libbpf/ebpf: Add example to `PT_REGS_SYSCALL_REGS`

go.mod, go.sum
Dependabot is complaining about a vulnerability in golang.org/x/net v0.38.0. This does not effect us in any real way, but its a good excuse to update all our dependencies to the latest version.
=> go.mod: Update all go dependencies

docs/linux/helper-function/bpf_get_current_pid_tgid.md, docs/linux/helper-function/bpf_get_current_uid_gid.md
This PR resolves issue #180 by correcting the extraction order for both `bpf_get_current_pid_tgid()` and `bpf_get_current_uid_gid()`. In the existing documentation, the code mistakenly reads the PID and TGID from the wrong 32-bit halves of the 64-bit return value. While investigating that issue, it was discovered that the same reversal also affects the `bpf_get_current_uid_gid()` helper.
**Changes included**
* Swap the high- and low-word interpretations for `bpf_get_current_pid_tgid()` so that TGID is extracted from the upper 32 bits and PID from the lower 32 bits.
* Apply the equivalent correction to `bpf_get_current_uid_gid()`, ensuring that GID is taken from the upper 32 bits and UID from the lower 32 bits.
**References**
* [bpf\_get\_current\_pid\_tgid in Linux …
=> bpf_get_current_* helpers: Fix reversed order of PID/TGID and UID/GID extraction

docs/linux/concepts/concurrency.md
The description of the `__sync_val_compare_and_swap` atomic op was incorrect, this commit rectifies the situation.
Fixes: #184
=> Fix description of `__sync_val_compare_and_swap`

docs/ebpf-library/libbpf/userspace/bpf_obj_get_info_by_fd.md
This patch corrects minor inaccuracies in the `bpf_obj_get_info_by_fd` documentation regarding `info_len` and the return value descriptions.
1. Clarifies that `info_len` acts as both input *and* output, with the syscall updating it to reflect the actual written data.
2. Fixes the return value description to match the implementation: `0` on success, negative error code on failure.
Changes are based on [`BPF_OBJ_GET_INFO_BY_FD`](https://docs.ebpf.io/linux/syscall/BPF_OBJ_GET_INFO_BY_FD/) and aligns with `libbpf` implementation in [`src/bpf.c:1144`](https://github.com/libbpf/libbpf/blob/master/src/bpf.c#L1144) and
here is a brief part of the implementation:
```c
int bpf_obj_get_info_by_fd(int bpf_fd, void *info, __u32 *info_len)
{
// ....
attr.info.info_len = *info_len;
// ....
if (!err) …
```
=> Fix minor issues in `bpf_obj_get_info_by_fd` documentation

docs/ebpf-library/libbpf/userspace/bpf_program__attach_cgroup.md, docs/linux/program-type/BPF_PROG_TYPE_LSM.md
1. Specify that the return values of LSM eBPF programs have different semantics when using the cgroup attachement type (source: https://lwn.net/Articles/893266/)
2. Add usage and example for the libbpf bpf_program__attach_cgroup.md function.
=> Improve Documentation for cgroup LSM attachement type

docs/linux/helper-function/bpf_skb_output.md, docs/linux/helper-function/bpf_xdp_output.md
Add examples for bpf_skb_output and bpf_xdp_output from Kernel sample files
=> [map_helpers/perf_event]: Add examples for bpf_skb_output and bpf_xdp_output

docs/linux/map-type/BPF_MAP_TYPE_LPM_TRIE.md
The L in LPM abbreviation stands for Longest not Largest.
=> BPF_MAP_TYPE_LPM_TRIE: correct what LPM stands for

docs/linux/helper-function/bpf_timer_cancel.md, docs/linux/helper-function/bpf_timer_init.md, docs/linux/helper-function/bpf_timer_set_callback.md, docs/linux/helper-function/bpf_timer_start.md
This adds an example covering all bpf_timers, I was not sure how to populate 'Usage' section of the helpers if any suggestion please let me know.
=> [docs/timers] add an example for all bpf_timers

docs/ebpf-library/libbpf/ebpf/BPF_KRETPROBE.md
The description contain two contradicting information:
* kretprobe macro can use the input args of the traced function
* kretprobe macro can only provide the return value (optionally)
Only the second information valid: kretprobe can't parse pt_regs properly. Fix the description accordingly.
=> Fix BPF_KRETPROBE macro description

docs/linux/program-type/BPF_PROG_TYPE_XDP.md
Fix spelling: change 'roughtly' to 'roughly' in XDP documentation
=> Fix spelling: change 'roughtly' to 'roughly' in XDP documentation
