isovalent/ebpf-docs

- docs/linux/program-type/BPF_PROG_TYPE_SYSCALL.md
- docs/linux/program-type/index.md
This PR adds a page for `BPF_PROG_TYPE_SYSCALL` to the program type.
> program-type: Add page for `BPF_PROG_TYPE_SYSCALL`

- data/helpers-functions.yaml
- docs/linux/helper-function/bpf_lwt_push_encap.md
- docs/linux/program-type/BPF_PROG_TYPE_LWT_IN.md
- docs/linux/program-type/BPF_PROG_TYPE_LWT_OUT.md
- docs/linux/program-type/BPF_PROG_TYPE_LWT_XMIT.md
- docs/linux/program-type/index.md
This PR adds the LWT_IN, LWT_OUT, and LWT_XMIT program type pages.
> program-type: Add LWT_IN, LWT_OUT, and LWT_XMIT program type pages

- docs/linux/helper-function/bpf_get_stackid.md
This PR adds usage and examples for the `bpf_get_stackid` helper function to retrieve the kernel or user stack id.
It further links to the more complete official Linux examples of `trace_event` and `offwaketime`.
> Add usage and examples for bpf_get_stackid helper

- docs/linux/helper-function/bpf_fib_lookup.md
- docs/linux/helper-function/bpf_ima_file_hash.md
- docs/linux/helper-function/bpf_ima_inode_hash.md
Update the descriptions of the helper functions.
> linux/helper-function: Update descriptions

- data/feature-versions.yaml
- docs/linux/map-type/BPF_MAP_TYPE_STRUCT_OPS.md
- docs/linux/syscall/BPF_MAP_CREATE.md
- tools/version-finder/patterns.yaml
Also added new attributes and flags found during the investigation to the map create syscall page.
> map-types: Populated `BPF_MAP_TYPE_STRUCT_OPS` map type page

- .aspell.en.pws
- docs/linux/concepts/SUMMARY.md
- docs/linux/concepts/dynptrs.md
- docs/linux/concepts/index.md
This PR adds a new concept page for dynptrs.
> linux/concepts: Add dynptrs concept page

- docs/ebpf-library/libbpf/SUMMARY.md
- docs/ebpf-library/libbpf/ebpf/SUMMARY.md
- docs/ebpf-library/libbpf/ebpf/__array.md
- docs/ebpf-library/libbpf/ebpf/__type.md
- docs/ebpf-library/libbpf/ebpf/__uint.md
- docs/ebpf-library/libbpf/ebpf/__ulong.md
- docs/ebpf-library/libbpf/ebpf/enum-libbpf_pin_type.md
- docs/ebpf-library/libbpf/ebpf/index.md
Adding pages for the BTF map macros.
> libbpf/ebpf: Add map macros

- .aspell.en.pws
- docs/linux/program-type/BPF_PROG_TYPE_KPROBE.md
Add new linking and attachment code
> Link creation code BPF_PROG_TYPE_KPROBE.md

- docs/ebpf-library/libbpf/ebpf/SUMMARY.md
- docs/ebpf-library/libbpf/ebpf/bpf_printk.md
- docs/ebpf-library/libbpf/ebpf/bpf_seq_printf.md
- docs/ebpf-library/libbpf/ebpf/bpf_snprintf.md
- docs/ebpf-library/libbpf/ebpf/index.md
This commit adds pages for the print helpers currntly available in the libbpf ebpf side library.
> libbpf/ebpf: Add pages for print helpers

- data/kfuncs.yaml
- docs/linux/kfuncs/bpf_xdp_get_xfrm_state.md
- docs/linux/kfuncs/bpf_xdp_xfrm_state_release.md
- docs/linux/kfuncs/hid_bpf_allocate_context.md
- docs/linux/kfuncs/hid_bpf_hw_output_report.md
- docs/linux/kfuncs/hid_bpf_hw_request.md
- docs/linux/kfuncs/hid_bpf_input_report.md
- docs/linux/kfuncs/hid_bpf_release_context.md
- docs/linux/program-type/BPF_PROG_TYPE_SCHED_ACT.md
- docs/linux/program-type/BPF_PROG_TYPE_SCHED_CLS.md
- docs/linux/program-type/BPF_PROG_TYPE_XDP.md
Hi @dylandreimerink 
I just created the PR to fix wrong info I found.
Thanks!
> fix: wrong supported program types for xdp xfrm kfuncs

- docs/ebpf-library/libbpf/ebpf/bpf_for.md
https://github.com/libbpf/libbpf/blob/master/src/bpf_helpers.h#L371-L383
shoutout Andrii Nakryiko for pointing it out
> update bpf_for to indicate exclusive end

- docs/linux/program-type/BPF_PROG_TYPE_LSM.md
- docs/linux/syscall/BPF_LINK_CREATE.md
> Improve attachment documentation for LSM program types

- docs/linux/helper-function/bpf_jiffies64.md
- docs/linux/helper-function/bpf_ktime_get_boot_ns.md
- docs/linux/helper-function/bpf_ktime_get_coarse_ns.md
- docs/linux/helper-function/bpf_ktime_get_ns.md
Hello. I added usage and example section for some pages of docs.
> Linux/helper-functions:  improve some pages

- docs/linux/helper-function/bpf_skb_output.md
BPF_PROG_TYPE_PERF_EVENT should be BPF_PROG_TYPE_RAW_TRACEPOINT
> Fix link on bpf_skb_output.md

- .aspell.en.pws
- data/feature-versions.yaml
- docs/linux/program-type/BPF_PROG_TYPE_KPROBE.md
- docs/linux/syscall/BPF_LINK_CREATE.md
- docs/linux/timeline/index.md
> linux/program-type: include session attachment to kprobe program type

- docs/linux/program-type/BPF_PROG_TYPE_KPROBE.md
- docs/linux/program-type/BPF_PROG_TYPE_LIRC_MODE2.md
- docs/linux/program-type/index.md
This PR adds more details to the LIRC_MODE2 program type page.
> linux/program-type: Expand LIRC_MODE2 page

- docs/linux/helper-function/bpf_probe_read_kernel.md
Add usage note and example for bpf_probe_read_kernel helper.
> helper-function: add usage and example for bpf_probe_read_kernel

- docs/ebpf-library/libbpf/ebpf/BPF_USDT.md
- docs/ebpf-library/libbpf/ebpf/SUMMARY.md
- docs/ebpf-library/libbpf/ebpf/bpf_usdt_arg.md
- docs/ebpf-library/libbpf/ebpf/bpf_usdt_arg_cnt.md
- docs/ebpf-library/libbpf/ebpf/bpf_usdt_arg_size.md
- docs/ebpf-library/libbpf/ebpf/bpf_usdt_cookie.md
- docs/ebpf-library/libbpf/ebpf/index.md
- docs/linux/concepts/SUMMARY.md
- docs/linux/concepts/index.md
- docs/linux/concepts/usdt.md
- docs/linux/program-type/BPF_PROG_TYPE_KPROBE.md
This PR adds a concept page for USDT probes and pages for the BPF side USDT functionality it provides.
Fixes: #122
> Add documentation for USDT probes

- docs/linux/helper-function/bpf_xdp_adjust_tail.md
Let's add some use cases and an example for bpf_xdp_adjust_tail helper.
> helper-function: add usage and example for bpf_xdp_adjust_tail

- .aspell.en.pws
- docs/concepts/index.md
added a small note about ELF: what it is and where its used
> docs/concepts: add details about ELF

- docs/linux/helper-function/bpf_get_current_task.md
add usage and example for  ```bpf_get_current_task```
> helper function update: bpf_get_current_task

- .aspell.en.pws
- docs/linux/helper-function/bpf_map_lookup_percpu_elem.md
update bpf_map_lookup_percpu_elem
> update map helpers: bpf_map_lookup_percpu_elem

- docs/ebpf-library/libbpf/userspace/bpf_obj_get_info_by_fd.md
Thanks a lot for such documentation! :)
> An example for `bpf_obj_get_info_by_fd`

- docs/linux/concepts/af_xdp.md
Some details changed around `XDP_SHARED_UMEM` usage for AF_XDP sockets. This commit reflects those changes in the documentation.
Fixes: #164
> linux/concepts/af_xdp.md: Correct `XDP_SHARED_UMEM` usage

- docs/linux/helper-function/bpf_map_lookup_elem.md
- docs/linux/helper-function/bpf_map_update_elem.md
added a working example for both helpers. Both are the same for now, let me know if you want a unique one for each.
> update generic map helpers with better examples

- docs/linux/helper-function/bpf_map_delete_elem.md
apologies for the small PRs, I will try to make a larger one next time. Thanks for the feedback
> Update bpf_map_delete_elem.md with an example
